version: "3.8"
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-test}
    container_name: app
    command: pytest
    environment:
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URL: postgresql://postgres:postgres@db:5432/core
      PORT: 8080
      REBASE_URL: $REBASE_URL
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data
