name: CD
on:
  push:
    branches-ignore: ["**"]
    tags: ["v*"]
  release:
    types: [published]
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: py-telegram-bot-starter-kit
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test target
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          load: true
          push: false
          tags: image:test
          target: test
      - name: Run tests
        run: make test name=image tag=test
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        run: .github/workflows/deploy_to_heroku.sh
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
