name: CI
on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
  build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build test target
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          load: true
          push: false
          tags: image:test
          target: test
      - name: Run tests
        run: make test name=image tag=test
      - name: Build release target
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          push: false
